open module com.spinyowl.spinygui.core {
  requires transitive org.joml;
  requires static lombok;
  requires org.lwjgl;
  requires org.lwjgl.natives;
  requires org.lwjgl.stb;
  requires org.lwjgl.stb.natives;
  requires org.lwjgl.yoga;
  requires org.lwjgl.yoga.natives;
  requires io.github.classgraph;
  requires transitive org.slf4j;
  requires transitive ch.qos.logback.core;
  requires transitive ch.qos.logback.classic;
  requires transitive java.xml;
  requires com.google.common;
  requires org.antlr.antlr4.runtime;
  requires org.apache.commons.lang3;
  requires org.apache.commons.io;

  exports com.spinyowl.spinygui.core;
  exports com.spinyowl.spinygui.core.animation;
  exports com.spinyowl.spinygui.core.event;
  exports com.spinyowl.spinygui.core.event.listener;
  exports com.spinyowl.spinygui.core.event.processor;
  exports com.spinyowl.spinygui.core.font;
  exports com.spinyowl.spinygui.core.input;
  exports com.spinyowl.spinygui.core.input.impl;
  exports com.spinyowl.spinygui.core.layout;
  exports com.spinyowl.spinygui.core.layout.impl;
  exports com.spinyowl.spinygui.core.node.intersection;
  exports com.spinyowl.spinygui.core.node.layout;
  exports com.spinyowl.spinygui.core.node;
  exports com.spinyowl.spinygui.core.parser;
  exports com.spinyowl.spinygui.core.parser.impl;
  exports com.spinyowl.spinygui.core.parser.impl.css.antlr;
  exports com.spinyowl.spinygui.core.parser.impl.css.visitor;
  exports com.spinyowl.spinygui.core.style;
  exports com.spinyowl.spinygui.core.style.manager;
  exports com.spinyowl.spinygui.core.style.stylesheet;
  exports com.spinyowl.spinygui.core.style.stylesheet.atrule;
  exports com.spinyowl.spinygui.core.style.stylesheet.impl;
  exports com.spinyowl.spinygui.core.style.stylesheet.property;
  exports com.spinyowl.spinygui.core.style.stylesheet.selector;
  exports com.spinyowl.spinygui.core.style.stylesheet.selector.combinator;
  exports com.spinyowl.spinygui.core.style.stylesheet.selector.pseudo_class;
  exports com.spinyowl.spinygui.core.style.stylesheet.selector.simple;
  exports com.spinyowl.spinygui.core.style.stylesheet.term;
  exports com.spinyowl.spinygui.core.style.stylesheet.util;
  exports com.spinyowl.spinygui.core.style.types;
  exports com.spinyowl.spinygui.core.style.types.background;
  exports com.spinyowl.spinygui.core.style.types.border;
  exports com.spinyowl.spinygui.core.style.types.flex;
  exports com.spinyowl.spinygui.core.style.types.length;
  exports com.spinyowl.spinygui.core.system.event;
  exports com.spinyowl.spinygui.core.system.event.listener;
  exports com.spinyowl.spinygui.core.system.event.processor;
  exports com.spinyowl.spinygui.core.system.event.provider;
  exports com.spinyowl.spinygui.core.system.font;
  exports com.spinyowl.spinygui.core.system.font.impl;
  exports com.spinyowl.spinygui.core.system.input;
  exports com.spinyowl.spinygui.core.time;
  exports com.spinyowl.spinygui.core.util;
}
